// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxJe0iM_pduAcu5h_uiE_jNiB-0joJJpo',
    appId: '1:16666218441:web:f50bd325eaf64a3249e218',
    messagingSenderId: '16666218441',
    projectId: 'tick-techh',
    authDomain: 'tick-techh.firebaseapp.com',
    storageBucket: 'tick-techh.appspot.com',
    measurementId: 'G-TLDE8VPKQB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAyJ9Z2Zw8SQt-T7gWUucGb3pwRxAZ9y0',
    appId: '1:16666218441:android:30c7cbdbdbe6c7b249e218',
    messagingSenderId: '16666218441',
    projectId: 'tick-techh',
    storageBucket: 'tick-techh.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwcpQj4THlcqKHAKYtFpy6GHURBNc8xS8',
    appId: '1:16666218441:ios:ca3ad1e00b5aea6749e218',
    messagingSenderId: '16666218441',
    projectId: 'tick-techh',
    storageBucket: 'tick-techh.appspot.com',
    iosBundleId: 'com.example.tickTechh',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwcpQj4THlcqKHAKYtFpy6GHURBNc8xS8',
    appId: '1:16666218441:ios:ca3ad1e00b5aea6749e218',
    messagingSenderId: '16666218441',
    projectId: 'tick-techh',
    storageBucket: 'tick-techh.appspot.com',
    iosBundleId: 'com.example.tickTechh',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxJe0iM_pduAcu5h_uiE_jNiB-0joJJpo',
    appId: '1:16666218441:web:ca8e99614502bc6f49e218',
    messagingSenderId: '16666218441',
    projectId: 'tick-techh',
    authDomain: 'tick-techh.firebaseapp.com',
    storageBucket: 'tick-techh.appspot.com',
    measurementId: 'G-S93HXVF7BM',
  );
}
